---
- name: Ejecutar Script Generacion  Estado Final
  shell: 'sh {{ dirwrk }}/gen_estado_final_AIX.sh'
  check_mode: no
  ignore_errors: yes
  tags:
    - estado
    - AIX

- name: Recuperar archivo de diskamp generado
  fetch:
    src: '{{ dirwrk }}/Estado_Config_{{ ansible_hostname }}' 
    dest: '{{ dirout }}/'
    flat: yes
    validate_checksum: no
  check_mode: no
  ignore_errors: yes
  tags:
    - recover
    - AIX
...
