---
- hosts: all
  remote_user: '{{ usrdoc }}'
  become: true
  become_flags: '-H -S'
  roles:
    - /etc/ansible/roles/Documentacion
  vars_files:
    - /etc/ansible/roles/Documentacion/vars/main.yml
...
