---
# defaults file for prepare-os-oracleDB

## Definir los prerrequisitos a instalar
odb21c: false
odb19c: false
odb18c: false
odb13c: false
odb12c: true
odb11g: false

## Activar configuraciones de para RAC1
enable_rac: true
## Definicion de repositorio para paquetes y respectiva activacion
enable_repo: false
REPO_RHEL: {
  name: "Repo_local_ath",
  description: "Red Hat Enterprise Linux 7 Server (RPMs) ATH",
  baseurl: "https://10.129.60.66/reporhn/rhel-7-server-rpms",
  state: "present",
  enabled: "yes",
  gpgcheck: "no",
  sslverify: "no"
  }

### Version de RHEL para actualizar el SO
OSVER: '{{ ansible_distribution_version }}'

## OS HOSTNAME
## La configuracion del hostname se hace definiendo la variable OSNAME en el inventario


OSNAME: iaacol8
DOMAIN: seti.com.co

### Definicion de servidores DNS que se alojaran en el fichero /etc/resolv.conf
enable_dns: false

NAMESERVERS:
  - 192.168.0.1
  
### Definicion de fichero hosts (SCAN, VIP, PRIVATE, PUBLIC).
### Configurar si esta definido enable_rac: True
FILE_HOSTS:
  - { ip: '{{ ansible_default_ipv4.address }}', name: '{{ OSNAME }}' }

### NTP CONFIG
### Activar el uso del servicio ntp
enable_ntp: False
ntp_config_server: [ 'saturno.unad.edu.co', '0.cl.ntp.edgeuno.com' ]
ntp_config_restrict:
  - '-4 default kod notrap nomodify nopeer noquery'
  - '-6 default kod notrap nomodify nopeer noquery'
  - '127.0.0.1'
  - '::1'

### Configuring Security­Enhanced Linux (SELinux)
SELINUX_CONF: {
  TARGET: "targeted",
  STATE: "permissive"
}

### Configuring Firewall Settings
enable_fwd: false
firewall_port: [ '22/tcp', '443/tcp', '1528/tcp', '5500/tcp' ]



pass_grid: '$6$JO4wnKpvhaHyVW$nzyKRD0rx0XJRyJp4uMhDqIAVw36I1lsVdXvixxuZxBv/2pSDsW9j4EvPSCgLVWgQIl7mvXjtVaBTs9UQTC.i.'  # pass=grid
pass_oracle: '$6$0Jv67Te5ZD$xmnj3Tc7wXCBbtMYCud46IP0g4xbVn9qUsWtArKPNlA.xyG1cwG452RQzxEEEvOcxvu18pPlFG3e.HDCU8h82.'    # pass=oracle

### Setting up DM-­Multipath
### solo uno de los dos debe estar en true al tiempo
enable_udev: false
enable_asmlib: true

### Usuarios BD y GRID
ora_user: 'oracle'
grid_user: 'grid'

### Configuracion Filesystems BD y GRID
enable_vg: true
ora_disk: 'vdc'
grid_disk: 'vdd'
exp_disk: 'vde'

LVM:
  - { pvs: '/dev/{{ ora_disk }}', vg: 'vg_ora', lv: 'lv_ora', mount: '/oracle', mount_owner: '{{ ora_user }}', mount_group: 'oinstall', mount_mode: '0755', mount_dump: 1, mount_passno: 2, mount_opts: 'defaults', fstype: 'xfs' }
  - { pvs: '/dev/{{ grid_disk }}', vg: 'vg_grid', lv: 'lv_grid', mount: '/grid', mount_owner: '{{ grid_user }}', mount_group: 'oinstall', mount_mode: '0755', mount_dump: 1, mount_passno: 2, mount_opts: 'defaults', fstype: 'xfs' }
  - { pvs: '/dev/{{ exp_disk }}', vg: 'vg_exp', lv: 'lv_exp', mount: '/exports', mount_owner: '{{ ora_user }}', mount_group: 'oinstall', mount_mode: '0755', mount_dump: 1, mount_passno: 2, mount_opts: 'defaults', fstype: 'xfs' }

### Discos ASMLIB
node_part: true
MPATHS:
  - { ALIAS: "vdf", ASMALIAS: 'ASM01' }
  - { ALIAS: "vdg", ASMALIAS: 'FRA01' }
  - { ALIAS: "vdh", ASMALIAS: 'ARC01' }

### Credenciales ASM
UDEV_CRED:
  - { USER: "grid", GROUP: "dba", MODE: "0660" }

ASM_CRED: 
  - { USER: "grid", GROUP: "dba", MODE: "0660" }

### User Accounts & Groups
ora_groups: {
  oinstall:  54321,
  dba: 54322,
  asmdba:  54323,
  asmoper: 54324,
  asmadmin:  54325,
  oper: 54326,
  backupdba: 54327,
  dgdba: 54328,
  kmdba: 54329,
  racdba: 54330
}
...
