### Listado de paquetes prerequisitos
rpm_list_oracle.12c:
  - bc
  - binutils
  - elfutils-libelf
  - elfutils-libelf-devel
  - fontconfig-devel
  - glibc
  - glibc-devel
  - ksh
  - libaio
  - libaio-devel
  - libXrender
  - libX11
  - libXau
  - libXi
  - libXtst
  - libgcc
  - libnsl
  - librdmacm
  - libstdc++
  - libstdc++-devel
  - libxcb
  - libibverbs
  - make
  - smartmontools
  - sysstat
  - net-tools
  - python3
  - python3-configshell
  - python3-rtslib
  - python3-six
  - targetcli
  - nfs-utils
  - gcc-c++
  - glibc-devel.i686
  - glibc.i686
  - libstdc++.i686
  - motif
  - motif-devel
  - redhat-lsb
  - redhat-lsb-core
  ### Paquetes X11
  - xorg-x11-xauth.x86_64
  - xorg-x11-server-utils.x86_64
  - xorg-x11-utils.x86_64
  ### Java
  - java-1.8.0-openjdk

###  Setting Virtual Memory
virtual_memory.12c: {
  vm.swappiness.12c: 1,
  vm.dirty_background_ratio.12c: 3,
  vm.dirty_ratio.12c: 80,
  vm.dirty_expire_centisecs.12c: 500,
  vm.dirty_writeback_centisecs.12c: 100
}
### Setting Shared Memory (SHMMAX, SHMALL, SHMMNI)
shm_memory.12c: {
  kernel.shmmax.12c: 8329226240,
  kernel.shmall.12c: 8329226240,
  kernel.shmmni.12c: 4096
}
###   Setting Semaphores (SEMMSL, SEMMNI, SEMMNS)
kernel_memory.12c: {
  kernel.sem.12c: '250 32000 100 128'
}
### Ephemeral Network Ports
port_memory.12c: {
  net.ipv4.ip_local_port_range.12c:  '9000 65500'
}
### Optimizing Network Settings
network_memory.12c: {
  net.core.rmem_default.12c: 262144,
  net.core.rmem_max.12c: 4194304,
  net.core.wmem_default.12c: 262144,
  net.core.wmem_max.12c: 1048576
}
### Increasing synchronous I/O Requests
io_memory.12c: {
  fs.aio-max-nr.12c: 1048576
}
### Increasing File Handles
file_memory.12c: {
  fs.file-max.12c: 6815744
}

kernel_ops_panic.12c: {
  kernel.panic_on_oops.12c: 1
}