# TASK: ALISTAMIENTO 1 SO
 
# t1 - name: Configurar en modo permissive el selinux -t1
# t2 - name: Instalar paquetes -t2
# t3 - name: Crear la partici칩n del disco para separar SO -t3
# t4 - name: Crear el vgroot -t4
# t5 - name: Crear LV's para vgroot -t5
# t6 - name: Crear formato xfs para los LV's -t6
# t7 - name: Crear directorios temporales -t7
# t8 - name: Montaje de puntos de filesystem temporales-t8
# t9 - name: Reinicio del SO para aplicar los cambios -t9
# t10- name: Copiar archivo que realizar치 el cp -ax -t10
# t11- name: Ejecutar script de copiado, renombrado y umount de temporales -t11
# t12- name: Desmonte de los puntos de filesystem temporales -t12
# t13- name: Montaje de los puntos de filesystem definitivos -t13
# t14- name: Reinicio del SO para aplicar los cambios -t14
# t15- name: Eliminar archivo -t15


---
- name: Alistamiento 1 SO
  hosts: all
   
  tasks:
  - name: Configurar en modo permissive el selinux -t1
    selinux:
        policy: targeted
        state: permissive
    when: ansible_distribution == "RedHat" or "OL" or "CentOS"
    tags:
      - t1

  - name: Instalar paquetes -t2
    yum:
      name: "{{ item }}"
      state: present
    when: ansible_distribution == "RedHat" or "OL" or "CentOS"
    loop:
      - parted
      - lvm2
    tags:
      - t2

  - name: Crear la partici칩n del disco para separar SO -t3
    parted:
      device: /dev/sdb
      number: 1
      flags: [ lvm ]
      state: present
    tags:
      - t3
  
  - name: Crear el vgroot -t4
    lvg:
        vg: vgroot
        pvs: /dev/sdb1
    tags:
      - t4

  - name: Crear LV's para vgroot -t5
    lvol:
        vg: vgroot
        lv: "{{ item.lv }}"
        size: "{{ item.size }}"
        state: present
    loop:
      - {lv: 'lvhome', size: '15g'}
      - {lv: 'lvvar', size: '5g'}
      - {lv: 'lvtmp', size: '15g'}
      - {lv: 'lvvartmp', size: '5g'}
      - {lv: 'lvvarlog', size: '5g'}
      - {lv: 'lvvarlogaudit', size: '5g'}
    tags:
      - t5

  - name: Crear formato xfs para los LV's -t6
    filesystem:
        fstype: xfs
        dev: /dev/vgroot/{{ item }}
    loop:
      - lvhome
      - lvvar
      - lvtmp
      - lvvartmp
      - lvvarlog
      - lvvarlogaudit
    tags:
      - t6

  - name: Crear directorios temporales -t7
    file:
        path: "{{ item }}"
        owner: root
        group: root
        state: directory
    loop:
      - /home1
      - /var1
      - /tmp1
      - /varlog
      - /varlogtmp
      - /varlogaudit
      - /root/scripts
    tags:
      - t7

  - name: Montaje de puntos de filesystem temporales-t8
    mount:
        path: "{{ item.path }}"
        src: "{{ item.dev }}"
        fstype: xfs
        opts: defaults
        state: mounted
    loop:
      - {path: '/var1', dev: '/dev/vgroot/lvvar'}
      - {path: '/home1', dev: '/dev/vgroot/lvhome'}
      - {path: '/tmp1', dev: '/dev/vgroot/lvtmp'}
      - {path: '/vartmp', dev: '/dev/vgroot/lvvartmp'}
      - {path: '/varlog', dev: '/dev/vgroot/lvvarlog'}
      - {path: '/varlogaudit', dev: '/dev/vgroot/lvvarlogaudit'}
    tags:
      - t8

  - name: Reinicio del SO para aplicar los cambios -t9
    reboot:
      post_reboot_delay: 30
    tags:
      - t9

  - name: Copiar archivo que realizar치 el cp -ax -t10
    copy:
      src: /home/provseti/scripts/cp_fs_so_umount.j2
      dest: /root/scripts/cp_fs_so_umount.sh
      mode: +x
    tags:
      - t10

  - name: Ejecutar script de copiado, renombrado y umount de temporales -t11
    shell: "/bin/bash /root/scripts/cp_fs_so_umount.sh >> /root/scripts/cp_f_so_umount.log"
    tags:
      - t11

  - name: Desmonte de los puntos de filesystem temporales -t12
    mount:
        path: "{{ item }}"
        state: absent
    loop:
      - /var1
      - /home1
      - /tmp1
      - /vartmp
      - /varlog
      - /varlogaudit
    tags:
      - t12

  - name: Montaje de los puntos de filesystem definitivos -t13
    mount:
        path: "{{ item.path }}"
        src: "{{ item.dev }}"
        fstype: xfs
        opts: defaults
        state: mounted
    loop:
      - {path: '/var', dev: '/dev/vgroot/lvvar'}
      - {path: '/home', dev: '/dev/vgroot/lvhome'}
      - {path: '/tmp', dev: '/dev/vgroot/lvtmp'}
      - {path: '/var/tmp', dev: '/dev/vgroot/lvvartmp'}
      - {path: '/var/log', dev: '/dev/vgroot/lvvarlog'}
      - {path: '/var/log/audit', dev: '/dev/vgroot/lvvarlogaudit'}
    tags:
      - t13

  - name: Reinicio del SO para aplicar los cambios -t14
    reboot:
      post_reboot_delay: 30
    tags:
      - t14

  - name: Eliminar archivo -t15
    file:
      path: /root/scripts/cp_fs_so_umount.sh
      state: absent
    tags:
      - t15
...