---
- name: Ajustar logs de sql
  hosts: all
  tasks:
  - name: Insertando lineas en ficheros sql
    block: 
     - blockinfile:
         path: "{{ item }}"
         insertafter: '^SPOOL log'
         block: |
           !export NLS_LANG=SPANISH_SPAIN.WE8ISO8859P15
           !export NLS_DATE_FORMAT=DD/MM/YYYY
           !echo $NLS_LANG
           !echo $NLS_DATE_FORMAT
       with_items:
#         - /home/oracle/LimspINF/db/2.4.1/check-structure.sql
#         - /home/oracle/LimspINF/db/2.4.1/instalar-base-sdp.sql
#         - /home/oracle/LimspINF/db/2.4.1/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.4.5/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.5.0/check-structure.sql
#         - /home/oracle/LimspINF/db/2.5.0/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.5.1/check-structure.sql
#         - /home/oracle/LimspINF/db/2.5.1/instalar-base-sdp.sql
#         - /home/oracle/LimspINF/db/2.5.1/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.5.8/change_to_default.sql
#         - /home/oracle/LimspINF/db/2.5.8/instalar-base-inf.sql
#         - /home/oracle/LimspINF/db/2.5.8/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.5.8/list_company.sql
#         - /home/oracle/LimspINF/db/2.5.9/instalar-base.sql
#         - /home/oracle/LimspINF/db/2.6.0/check-structure.sql
#         - /home/oracle/LimspINF/db/2.6.0/instalar-base-sdp.sql
#         - /home/oracle/LimspINF/db/2.6.0/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/activar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-rebuild-hist.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-rebuild-temp.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/email-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/email-instalar-buscador.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-binary_store-DB.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-contabilidad.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-encriptacion_usuarios.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestionperfiles.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestionriesgo.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestor-contenido.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-idioma-gui.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-mailerror.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-massivemonitor.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiagentes.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiempresa.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiusuario.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/listar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/pns-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-establecer-operadora-defecto.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-buscador.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-enviopushMMS.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-modulo-descargas.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-prefijo-operadora.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/tweet-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.05/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/activar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-gestor-contenido.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/listar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/reasignar-plantillas.sql
         - /home/oracle/LimspSDP/db/3.9.5.18/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.35/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.43/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.73/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.95/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.96/instalar-base.sql
     - lineinfile:
         path: "{{ item }}"
         state: absent
         regexp: '#.*ANSIBLE MANAGED BLOCK'
       with_items:
#        - /home/oracle/LimspINF/db/2.4.1/check-structure.sql
#        - /home/oracle/LimspINF/db/2.4.1/instalar-base-sdp.sql
#        - /home/oracle/LimspINF/db/2.4.1/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.4.5/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.5.0/check-structure.sql
#        - /home/oracle/LimspINF/db/2.5.0/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.5.1/check-structure.sql
#        - /home/oracle/LimspINF/db/2.5.1/instalar-base-sdp.sql
#        - /home/oracle/LimspINF/db/2.5.1/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.5.8/change_to_default.sql
#        - /home/oracle/LimspINF/db/2.5.8/instalar-base-inf.sql
#        - /home/oracle/LimspINF/db/2.5.8/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.5.8/list_company.sql
#        - /home/oracle/LimspINF/db/2.5.9/instalar-base.sql
#        - /home/oracle/LimspINF/db/2.6.0/check-structure.sql
#        - /home/oracle/LimspINF/db/2.6.0/instalar-base-sdp.sql
#        - /home/oracle/LimspINF/db/2.6.0/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/activar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-rebuild-hist.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-rebuild-temp.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/email-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/email-instalar-buscador.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-binary_store-DB.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-contabilidad.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-encriptacion_usuarios.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestionperfiles.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestionriesgo.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-gestor-contenido.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-idioma-gui.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-mailerror.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-massivemonitor.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiagentes.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiempresa.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/instalar-multiusuario.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/listar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/pns-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-establecer-operadora-defecto.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-buscador.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-enviopushMMS.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-modulo-descargas.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/sms-instalar-prefijo-operadora.sql
         - /home/oracle/LimspSDP/db/3.9.5.00/tweet-instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.05/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.111/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/activar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/check-structure.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-gestor-contenido.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/listar-idioma.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/pre-validation.sql
         - /home/oracle/LimspSDP/db/3.9.5.15/reasignar-plantillas.sql
         - /home/oracle/LimspSDP/db/3.9.5.18/instalar-groupsender.sql
         - /home/oracle/LimspSDP/db/3.9.5.35/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.43/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.73/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.95/instalar-base.sql
         - /home/oracle/LimspSDP/db/3.9.5.96/instalar-base.sql
